<?php
/**
 * Created by PhpStorm.
 * Author:
 * Date: 2017/4/13
 * Time: 下午2:17
 */

namespace app\frontend\modules\refund\controllers;


use app\common\components\ApiController;
use app\common\exceptions\AdminException;
use app\common\exceptions\AppException;
use app\common\models\Order;
use app\common\modules\refund\services\RefundService;
use app\frontend\modules\refund\models\RefundApply;
use app\frontend\modules\refund\services\RefundMessageService;
use app\frontend\modules\refund\services\RefundOperationService;

/**
 * 统一售后操作接口
 * Class OperationController
 * @package app\frontend\modules\refund\controllers
 */
class OperationController extends ApiController
{
    public $transactionActions = ['*'];


    public function preAction()
    {
        parent::preAction(); // TODO: Change the autogenerated stub

        $this->validate([
            'refund_id' => 'required|filled|integer',
        ]);
        $this->refundApply = RefundApply::find(request()->input('refund_id'));
        if (!isset($this->refundApply)) {
            throw new AppException('售后申请记录不存在');
        }

        if ($this->refundApply->uid != \YunShop::app()->getMemberId()) {
            throw new AppException('无效申请,该订单属于其他用户');
        }
    }

    public function batchSend()
    {

        $refund_id = request()->input('refund_id');

        RefundOperationService::batchSendBack(['refund_id' => $refund_id]);

        return $this->successJson('操作成功');
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     * @throws \app\common\exceptions\AppException
     * @throws \app\common\exceptions\ShopException
     */
    public function send()
    {
        $this->validate([
            'express_company_code' => 'required|string',
            'express_company_name' => 'required|string',
            'express_sn' => 'required|filled|string',
        ]);
        RefundOperationService::refundSendBack(['refund_id'=> request()->input('refund_id')]);
        return $this->successJson('操作成功');
    }

    /**
     * @return \Illuminate\Http\JsonResponse
     * @throws \app\common\exceptions\AppException
     * @throws \app\common\exceptions\ShopException
     */
    public function complete()
    {
        RefundOperationService::refundExchangeComplete(['refund_id'=> request()->input('refund_id')]);

        return $this->successJson('操作成功');

    }

    /**
     * @return \Illuminate\Http\JsonResponse
     * @throws \app\common\exceptions\AppException
     * @throws \app\common\exceptions\ShopException
     */
    public function cancel()
    {
        $refund_id = request()->input('refund_id');
        $refund = \app\common\models\refund\RefundApply::where('id',$refund_id)->first();
        if(in_array($refund->status,[6,7])){
            throw new AppException('订单已完成退款');
        }
        $orderIds = Order::where('parent_id',$refund->order_id)->pluck('id')->toArray();
        $refundIds = \app\common\models\refund\RefundApply::whereIn('order_id',$orderIds)->where('status','!=',-2)->pluck('id')->toArray();
        $refundIds = array_merge($refundIds,[$refund_id]);
        foreach ($refundIds as $refundId){
            RefundOperationService::refundCancel(['refund_id'=> $refundId]);
        }
        $refund->order->refund_status = 0;
        $refund->order->save();
        return $this->successJson('操作成功');

    }

}