<?php

$return_data = [
    'columns' => [
        '订单信息' => [
            'id' => '订单id',
            'order_sn' => '订单编号',
            'pay_sn' => '支付单号',
            'uid' => '会员ID',
            'nickname' => '粉丝昵称',
            'address_name' => '收货人姓名',
            'mobile' => '联系电话',
            'province' => '省',
            'city' => '市',
            'area' => '区',
            'address' => '收货地址',
            'goods_title' => '商品名称',
            'alias' => '商品简称',
            'goods_sn' => '商品编码',
            'product_sn' => '商品条码',
            'total' => '商品数量',
            'first_cated' => '一级分类',
            'second_cate' => '二级分类',
            'third_cate' => '三级分类',
            'vip_price' => '会员价',
            'pay_type_name' => '支付方式',
            'deduction' => '抵扣金额',
            'coupon' => '优惠券优惠',
            'enoughReduce' => '全场满减优惠',
            'singleEnoughReduce' => '单品满减优惠',
            'goods_price' => '商品小计',
            'dispatch_price' => '运费',
            'price' => '应收款',
            'cost_price' => '成本价',
            'status_name' => '状态',
            'create_time' => '下单时间',
            'pay_time' => '付款时间',
            'send_time' => '发货时间',
            'finish_time' => '完成时间',
            'company' => '快递公司',
            'express_sn' => '快递单号',
            'remark' => '订单备注',
            'note' => '用户备注',
            'fistOrder' => '首单',
            'realname' => '真实姓名',
            'idcard' => '身份证',
            'auditor' => '核销员',
            'additional' => '附加',
            'export_refund_name' => '订单提示状态',
            'invoice_type' => '发票类型',
            'rise_type' => '发票抬头',
            'collect_name' => '单位/抬头名称',
            'gmf_taxpayer' => '税号',
            'content' => '发票内容',
            'gmf_bank' => '开户银行',
            'gmf_bank_admin' => '银行账号',
            'gmf_address' => '注册地址',
            'gmf_mobile' => '注册电话',
            'col_name' => '收票人姓名',
            'col_mobile' => '收票人手机号',
            'col_address' => '收票人地址',
            'email' => '邮箱',
            'delivery_day' => '配送日期',
            'delivery_time' => '配送时间',

            'goodsContribution' => '商品贡献值',
            'goodsContributionStatus' => '商品贡献值状态',
        ]
    ]
];

return $return_data;