<?php
return
    [
        'columns' => [
            '订单信息' => [
                'id' => '订单ID',
                'orderSn' => '订单编号',
                'paySn' => '支付单号',
                'payType' => '支付方式',
                'discountPrice' => '抵扣金额',
                'couponDiscount' => '优惠券优惠',
                'allDiscount' => '全场满减优惠',
                'oneDiscount' => '单品满减优惠',
                'productSubtotal' => '商品小计',
                'freight' => '运费',
                'price' => '应收款',
                'refundPrice' => '已退款金额',
                'lastPrice' => '剩余金额',
                'status' => '订单状态',
                'refundStatus' => '售后状态',
                'createTime' => '下单时间',
                'payTime' => '付款时间',
                'sendTime' => '发货时间',
                'receiptTime' => '完成时间',
                'expressCompany' => '快递公司',
                'expressSn' => '快递单号',
                'orderRemark' => '订单备注',
                'remark' => '用户备注',
                'firstOrder' => '首单',
                'underwriter' => '核销员',
                'addition' => '附加',
                'remindStatus' => '订单提示状态',
                'deliveryDate' => '配送日期',
                'deliveryTime' => '配送时间',
                'goodsContribution' => '商品贡献值',
                'goodsContributionStatus' => '商品贡献值状态',
            ],
            '商品信息' => [
                'goodsTitle' => '商品名称',
                'goodsShort' => '商品简称',
                'goodsOption' => '商品规格',
                'goodsCode' => '商品编码',
                'goodsBarcode' => '商品条码',
                'goodsNum' => '商品数量',
                'refundNum' => '退款数量',
                'lastNum' => '剩余数量',
                'firstCategory' => '一级分类',
                'secondCategory' => '二级分类',
                'thirdCategory' => '三级分类',
                'memberPrice' => '会员价',
                'goodsCostPrice' => '成本价',
                'profit' => '利润',
                'diyForm' => '自定义表单',
                'goodsSource' => '商品来源',
                'supplierName' => '供应商名称',
                'storeName' => '门店名称'
            ],
            '用户信息' => [
                'memberId' => '会员ID',
                'nickname' => '会员昵称',
                'mobile' => '会员绑定手机号',
                'consigneeName' => '收货人姓名',
                'consigneeMobile' => '收货人手机号',
                'province' => '收货地址省份',
                'city' => '收货地址城市',
                'area' => '收货地址地区',
                'address' => '收货地址',
                'realName' => '真实姓名',
                'idCard' => '身份证',
                'diyMember' => '自定义字段名称'
            ],
            '其他信息' => [
                'pickName' => '自提点名称',
                'pickPerson' => '自提点负责人',
                'pickMobile' => '自提点电话',
                'shopPoint' => '平台抽点',
                'firstCommission' => '一级佣金(分销)',
                'secondCommission' => '二级佣金(分销)',
                //'shareholder' => '股东',
                //'teamDividendLevel' => '经销商等级'
            ],
            '发票' => [
                'invoiceType' => '发票类型',
                'invoice' => '发票抬头',
                'invoiceCompany' => '单位/抬头名称',
                'taxCode' => '税号',
                'invoiceContent' => '发票内容',
                'openBank' => '开户银行',
                'accountBank' => '银行账号',
                'registerAddress' => '注册地址',
                'registerMobile' => '注册电话',
                'invoiceName' => '收票人姓名',
                'invoiceMobile' => '收票人手机号',
                'invoiceAddress' => '收票人地址',
                'invoiceEmail' => '邮箱',
            ],
        ],
        'action' =>\Yunshop\YzSupplyCamiloResources\exports\action\YzSupplyCamiloResourcesOrder::class
    ];