<?php

namespace app\outside\modules\order\models;

class Order extends \app\common\models\Order
{
    public $appends = [];
    public $with = [];

    public static function getList($search = [])
    {
        $model = self::uniacid();

        $model->select(['id','order_sn','uid','price','create_time','pay_time','send_time','finish_time','cancel_time',
            'discount_price','deduction_price','dispatch_price'
        ]);

        $model->whereIn('yz_order.plugin_id',$search['plugin_ids']);

        if (isset($search['uid'])) {
            $model->where('yz_order.uid', $search['uid']);
        }

        if (isset($search['create_time'])) {
            $model->where('yz_order.create_time', '>=',$search['create_time']);
        }

        $model->with(['orderGoods' => function($q) {
            $q->select(['goods_id', 'goods_option_id','title','goods_option_title','order_id','total','goods_price','payment_amount','thumb']);
        },'belongsToMember' => function ($q) {
            $q->select(['uid','mobile','nickname','avatar']);
        },'orderAddress']);

        return $model;
    }

    public function orderAddress()
    {
        return $this->hasOne(OrderAddressApi::class, 'order_id', 'id'); // TODO: Change the autogenerated stub
    }

    public function orderGoods()
    {
        return $this->hasMany(OrderGoods::class, 'order_id', 'id'); // TODO: Change the autogenerated stub
    }
}